### ISSUE TITLE
podSelector in networkPolicy should be the exactly the same as selector on k8s Service

### ISSUE THREAD

**Issue by tikhon-opsfleet** [aws/amazon-network-policy-controller-k8s#147]
### What happened:

Summary: Currently when creating a NetworkPolicy podSelector in rule should be exactly the same as selector on k8s Service, if podSelector technically correct but different from k8s service selector access will not be allowed.
I think it is not correct behavior.

### How to reproduce it (as minimally and precisely as possible):

2 pods (backend / frontend) + service for backend:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend-container
    image: docker.io/byrnedo/alpine-curl:0.1.8
    command: [ "/bin/ash", "-c", "sleep 1000000000" ]
    
---

apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
    test: test
spec:
  containers:
  - name: backend-container
    env:
    - name: PORT
      value: "8080"
    ports:
    - containerPort: 8080
    image: docker.io/cilium/json-mock:1.2
    
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 8080

```

As you can see backend pod have 2 labels (**app=backend** and **test=test**), k8s service using **app=backend** in selector.

Network policies:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: backend
spec:
  podSelector:
    matchLabels:
      app: backend
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: frontend
  policyTypes:
  - Ingress
  - Egress

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            test: test
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system

```

If we trying to reach backend from frontend pod (using command like "k exec frontend -- curl http://backend:8080") if will not work because last networkPolicy using this **test=test** selector (which is technically right but not the same as for k8s service).

If we changing podSelector label to **app=backend** in the last networkPolicy like this:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: backend
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
```

it started to work as expected.

### Environment:

Kubernetes version (use kubectl version): Server Version: v1.30.6-eks-7f9249a
CNI Version: amazon-k8s-cni:v1.19.0-eksbuild.1
Network Policy Agent Version: aws-network-policy-agent:v1.1.5-eksbuild.1
OS (e.g: cat /etc/os-release): Amazon Linux 2
